/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GlobalStats = IDL.Record({
  'totalPlayers' : IDL.Nat,
  'totalPrestige' : IDL.Nat,
  'totalClicks' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'prestigeCount' : IDL.Nat,
  'name' : IDL.Text,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GlobalStats = IDL.Record({
    'totalPlayers' : IDL.Nat,
    'totalPrestige' : IDL.Nat,
    'totalClicks' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'prestigeCount' : IDL.Nat,
    'name' : IDL.Text,
    'score' : IDL.Nat,
  });
  
  return IDL.Service({
    'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };